class PhysicalElements:
    LAPTOP = "laptop"
    SMARTPHONE = "smartphone"
    SCREEN = "screen"
    BOX = "box"
    WIFI_NETWORK = "wifi_network"
    MOBILE_NETWORK = "mobile_network"
    SERVERLESS = "serverless"
    ON_PREMISE = "on_premise"
    AUTOSCALING = "autoscaling"
    WEB_SERVER = "web_server"
    STORAGE = "storage"
